mutation SIGN_UP($auth: AuthInput!) {
  signup(auth: $auth) {
    user {
      id
    }
    access_token
    refresh_token
  }
}

mutation UPDATE_TOKEN {
  updateToken {
    access_token
    refresh_token
  }
}
